/**
 * Standalone (non-Markdown) posts.
 *
 * Two of the Jekyll posts are full Jupyter notebook HTML exports — their own
 * `<!DOCTYPE html>`, inlined Bootstrap CSS and MathJax config. They cannot be
 * rendered inside the post layout, so `scripts/migrate.mjs` writes them to
 * `src/standalone-posts/` and records their metadata in `manifest.json`.
 *
 * Routing them through src/pages/[...slug].astro instead of dropping them in
 * public/ keeps them in the sitemap, in post listings, and previewable by
 * `astro dev` (which does not do directory-index resolution for public/).
 */

export interface StandalonePost {
  /** Exact published path, e.g. "tech/spam_deep_learning". */
  slug: string;
  /** File name inside src/standalone-posts/. */
  file: string;
  title: string;
  /** ISO date string, YYYY-MM-DD. */
  date: string;
  description: string;
  /** Jekyll's `post.excerpt`, used by list views. */
  excerpt: string;
  categories: string[];
  tags: string[];
  draft: boolean;
}

// Manifest is generated by `npm run migrate` and committed alongside the posts.
import manifest from '../standalone-posts/manifest.json';
import { NAV, SITE } from './site';

const entries = manifest as StandalonePost[];

const documents = import.meta.glob('../standalone-posts/*.html', {
  query: '?raw',
  import: 'default',
});

/** Published standalone posts, for route generation and listings. */
export function getStandalonePosts(): StandalonePost[] {
  return entries.filter((entry) => !entry.draft);
}

/** Every standalone post including drafts. */
export function getAllStandalonePosts(): StandalonePost[] {
  return entries;
}

export async function readStandaloneHtml(file: string): Promise<string> {
  const key = `../standalone-posts/${file}`;
  const load = Object.hasOwn(documents, key) ? documents[key] : undefined;
  if (!load) {
    throw new Error(
      `Standalone post document not found: src/standalone-posts/${file} — re-run \`npm run migrate\`.`,
    );
  }
  return await load();
}

/**
 * A minimal navigation bar for standalone notebook documents.
 *
 * They are complete HTML documents carrying their own Bootstrap/Jupyter CSS, so
 * BaseLayout cannot wrap them and SiteNav cannot be used — the Jekyll build
 * served them as orphans too (no masthead in _site/tech/spam_deep_learning/).
 *
 * It carries no colours of its own (`border-bottom: 1px solid` falls back to
 * currentColor), so nothing here duplicates the global.css tokens, which this
 * document does not load. Kept as a single string in a single function so Phase 5
 * can replace it with a real stylesheet without hunting for markup.
 */
export function standaloneChrome(): string {
  const links = NAV.map((item) =>
    item.external
      ? `<a href="${item.url}" target="_blank" rel="noopener noreferrer">${item.title}</a>`
      : `<a href="${item.url}">${item.title}</a>`,
  ).join(' &middot; ');

  return (
    '<div class="standalone-bar" style="padding:.6rem 1rem;border-bottom:1px solid;font-size:14px">' +
    `<strong><a href="/">${SITE.title}</a></strong> &middot; ${links}` +
    '</div>'
  );
}

/** Inserts the bar just inside `<body>`; returns the document untouched if it has none. */
export function injectStandaloneChrome(html: string, bar: string): string {
  if (!/<body[^>]*>/i.test(html)) return html;
  return html.replace(/<body([^>]*)>/i, `<body$1>${bar}`);
}
