# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Seeking Wisdom"
title_separator          : "-"
name                     : "Sanjay Meena"
description              : "Blog on Equities, Tech, Books"
url                      : http://localhost:4000
baseurl                  :
base_path                : http://localhost:4000 #"http://sanjaymeena.io"
teaser                   : # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "disqus"
  disqus:
    shortname            : "sanjaymeenaio"
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                : 104927903264352
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : sanjaymeena
facebook:
  username               : sanjaymeena
  app_id                 : 104927903264352
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Person
  name                   : Sanjay Meena
  links: # An array of links to social media profiles
    - "https://twitter.com/sanjaymeena"
    - "https://www.linkedin.com/in/sanjay-meena-7546058"
    - "https://plus.google.com/u/0/+sanjaymeena123"

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-78154345-1"

# Google AdSense
google_ad_client         :
google_ad_slot           :


# Site Author
author:
  name             : "Sanjay Meena"
  avatar           : "bio.jpg"
  bio              : "Data Scientist"
  location         : "Taipei , Taiwan"
  email            : sanjaymeena@gmail.com
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : sanjaymeena
  google_plus      : sanjaymeena123
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "sanjay-meena-7546058"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : sanjaymeena
  vine             :
  weibo            :
  xing             :
  youtube          :




# Default settings
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      subscribe: true
      #share: twitter linkedin facebook # Sharing on twitter ,facebook and LinkedIn by default

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      subscribe: true

# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
#timezone: America/New_York # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# jekyll-press config
jekyll-press:
  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options



# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - gulpfile.js
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones



#
# jekyll-press:
#   exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
#   js_options: {}      # js minifier options
#   css_options: {}     # css minifier options
#   html_options: {}    # html minifier options

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  #- jekyll-press

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  #- jekyll-press


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /


# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

  ignore:
    envs: development
