import rss from '@astrojs/rss';
import type { APIContext } from 'astro';
import { SITE } from '../../lib/site';

const PLATFORMS = ['twitter', 'facebook', 'linkedin'];

export function getStaticPaths() {
  return PLATFORMS.map((platform) => ({ params: { platform } }));
}

/**
 * Vestigial — kept only so three live URLs do not start returning 404.
 *
 * These were generated by _layouts/social-feeds.xml, which emitted only posts
 * whose `share` frontmatter named the platform. Nothing sets `share` to those
 * values, so all three feeds were already empty on the live site (verified: 0
 * <item> elements in _site/social-feeds/*.xml) and the migration brief drops the
 * `share` field entirely. Delete this file if no automation polls the URLs.
 */
export async function GET(context: APIContext) {
  return rss({
    title: SITE.title,
    description: SITE.description,
    site: context.site ?? new URL(SITE.url),
    items: [],
  });
}
